file_format: "1"
id: kraken
name: Krakne
type: shield
url: https://github.com/kalikaliasfdsf/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - corne_left
  - corne_right